-- RISE Nutrition Tracker: Food Database Seed
-- Seeds the `food_database` table with 200+ foods used by the portion-based
-- protein tracker. Items span proteins, carbs, vegetables, fruits, dairy &
-- drinks, and common HK/Chinese composite dishes.
-- Run this AFTER the `food_database` table exists in Supabase Postgres.
-- All Chinese names use Simplified characters. Booleans are lowercase.
-- Protein values are grams for the given visual portion.

INSERT INTO food_database (name, name_zh, category, portion_label, protein_per_portion, common_in_hk, active) VALUES
-- ============== PROTEINS (~60) ==============
('Chicken breast', '鸡胸肉', 'protein', '1 palm', 30, false, true),
('Chicken thigh', '鸡腿肉', 'protein', '1 palm', 25, false, true),
('Grilled fish fillet', '烤鱼柳', 'protein', '1 palm', 28, false, true),
('Salmon', '三文鱼', 'protein', '1 palm', 32, false, true),
('Canned tuna', '罐装吞拿鱼', 'protein', '1 small can', 20, false, true),
('Beef steak', '牛扒', 'protein', '1 palm', 36, false, true),
('Ground beef', '牛肉碎', 'protein', '1 cup cooked', 30, false, true),
('Pork chop', '猪扒', 'protein', '1 piece', 28, false, true),
('Pork belly', '五花肉', 'protein', '3 slices', 15, true, true),
('BBQ pork / char siu', '叉烧', 'protein', '1 palm', 25, true, true),
('Roast goose', '烧鹅', 'protein', '1 palm', 22, true, true),
('Roast duck', '烧鸭', 'protein', '1 palm', 22, true, true),
('Steamed fish', '清蒸鱼', 'protein', '1 medium whole', 35, true, true),
('Fish balls', '鱼蛋', 'protein', '6 pieces', 12, true, true),
('Shrimp', '虾', 'protein', '10 medium', 18, false, true),
('Squid', '鱿鱼', 'protein', '1 palm', 18, false, true),
('Eggs', '鸡蛋', 'protein', '1 large', 6, false, true),
('Tofu, firm', '老豆腐', 'protein', '1 block', 20, false, true),
('Tofu, soft/silken', '嫩豆腐', 'protein', '1 block', 8, true, true),
('Soy milk, unsweetened', '无糖豆浆', 'protein', '1 cup', 7, true, true),
('Edamame', '毛豆', 'protein', '1 cup', 17, false, true),
('Tempeh', '天贝', 'protein', '1 palm', 16, false, true),
('Protein shake', '蛋白奶昔', 'protein', '1 scoop', 25, false, true),
('Greek yogurt', '希腊酸奶', 'protein', '1 cup', 15, false, true),
('Cottage cheese', '农家干酪', 'protein', '1 cup', 24, false, true),
('Turkey breast', '火鸡胸肉', 'protein', '1 palm', 28, false, true),
('Lamb chop', '羊扒', 'protein', '1 piece', 25, false, true),
('Beef brisket', '牛腩', 'protein', '1 palm', 28, true, true),
('Beef tendon', '牛筋', 'protein', '1 bowl', 15, true, true),
('Century egg', '皮蛋', 'protein', '1 piece', 5, true, true),
('Beef meatballs', '牛肉丸', 'protein', '4 pieces', 14, true, true),
('Salted egg', '咸蛋', 'protein', '1 piece', 7, true, true),
('Pork mince', '猪肉碎', 'protein', '1 cup cooked', 26, true, true),
('Chicken wings', '鸡翅', 'protein', '3 pieces', 18, true, true),
('Soy sauce chicken', '豉油鸡', 'protein', '1 palm', 24, true, true),
('White cut chicken', '白切鸡', 'protein', '1 palm', 25, true, true),
('Drunken chicken', '醉鸡', 'protein', '1 palm', 23, true, true),
('Chicken feet', '凤爪', 'protein', '6 pieces', 12, true, true),
('Pork ribs', '排骨', 'protein', '1 palm', 22, true, true),
('Sweet and sour pork', '咕噜肉', 'protein', '1 plate', 22, true, true),
('Lion''s head meatballs', '狮子头', 'protein', '2 pieces', 20, true, true),
('Chinese sausage / lap cheong', '腊肠', 'protein', '1 link', 8, true, true),
('Chinese ham', '金华火腿', 'protein', '2 slices', 10, true, true),
('Dried fish', '咸鱼干', 'protein', '1 palm', 25, true, true),
('Fish skin', '鱼皮', 'protein', '1 bowl', 14, true, true),
('Pork floss', '肉松', 'protein', '2 tbsp', 6, true, true),
('Salted fish', '咸鱼', 'protein', '1 palm', 22, true, true),
('Abalone', '鲍鱼', 'protein', '1 piece', 18, true, true),
('Scallops', '带子', 'protein', '4 pieces', 16, true, true),
('Mussels', '青口', 'protein', '8 pieces', 16, false, true),
('Clams', '蛤蜊', 'protein', '1 cup', 14, false, true),
('Oysters', '蚝', 'protein', '6 pieces', 14, true, true),
('King prawns', '大虾', 'protein', '5 pieces', 22, true, true),
('Crab', '蟹', 'protein', '1 medium', 20, true, true),
('Lobster', '龙虾', 'protein', '1 small tail', 22, false, true),
('Anchovies', '凤尾鱼', 'protein', '5 fillets', 8, false, true),
('Sardines', '沙丁鱼', 'protein', '1 small can', 22, false, true),
('Mackerel', '鲭鱼', 'protein', '1 palm', 26, false, true),
('Cod', '鳕鱼', 'protein', '1 palm', 24, false, true),
('Sea bass', '鲈鱼', 'protein', '1 palm', 26, true, true),
('Sole fish', '龙利鱼', 'protein', '1 palm', 22, false, true),
('Halibut', '比目鱼', 'protein', '1 palm', 28, false, true),
('Tilapia', '罗非鱼', 'protein', '1 palm', 26, false, true),
('Smoked salmon', '烟三文鱼', 'protein', '3 slices', 16, false, true),
('Deli ham', '火腿', 'protein', '3 slices', 10, false, true),
('Bacon', '培根', 'protein', '3 strips', 9, false, true),
('Hot dog', '热狗肠', 'protein', '1 link', 7, false, true),
('Salami', '萨拉米', 'protein', '5 slices', 12, false, true),
('Duck breast', '鸭胸', 'protein', '1 palm', 26, true, true),
('Quail', '鹌鹑', 'protein', '1 whole', 18, true, true),
('Frog legs', '田鸡', 'protein', '1 plate', 22, true, true),
('Pigeon', '乳鸽', 'protein', '1 whole', 20, true, true),
('Black bean tofu skin', '腐皮', 'protein', '1 sheet', 8, true, true),
('Fried tofu puffs', '豆卜', 'protein', '6 pieces', 10, true, true),

-- ============== CARBS (~50) ==============
('White rice', '白饭', 'carb', '1 bowl', 4, true, true),
('Brown rice', '糙米饭', 'carb', '1 bowl', 5, false, true),
('Congee / jook', '粥', 'carb', '1 bowl', 3, true, true),
('Noodles', '面条', 'carb', '1 bowl', 7, true, true),
('Rice noodles / ho fun', '河粉', 'carb', '1 bowl', 3, true, true),
('Instant noodles', '公仔面', 'carb', '1 pack', 8, true, true),
('Bread, white', '白面包', 'carb', '2 slices', 5, false, true),
('Bread, whole wheat', '全麦面包', 'carb', '2 slices', 7, false, true),
('Bagel', '贝果', 'carb', '1 piece', 10, false, true),
('Oatmeal', '燕麦粥', 'carb', '1 bowl', 6, false, true),
('Pasta', '意粉', 'carb', '1 cup cooked', 8, false, true),
('Sweet potato', '番薯', 'carb', '1 medium', 2, false, true),
('Potato', '薯仔', 'carb', '1 medium', 4, false, true),
('Corn on the cob', '粟米', 'carb', '1 ear', 4, false, true),
('Mantou / steamed bun', '馒头', 'carb', '1 piece', 4, true, true),
('Baozi / steamed stuffed bun', '包子', 'carb', '1 piece', 6, true, true),
('Wonton', '云吞', 'carb', '8 pieces', 8, true, true),
('Fried rice', '炒饭', 'carb', '1 plate', 8, true, true),
('Fried noodles', '炒面', 'carb', '1 plate', 10, true, true),
('French fries', '薯条', 'carb', '1 medium', 4, false, true),
('Wrap / tortilla', '卷饼', 'carb', '1 piece', 4, false, true),
('Glutinous rice', '糯米饭', 'carb', '1 bowl', 5, true, true),
('Fried glutinous rice', '生炒糯米饭', 'carb', '1 plate', 8, true, true),
('Rice cake / nian gao', '年糕', 'carb', '3 slices', 3, true, true),
('Lo mai gai', '糯米鸡', 'carb', '1 piece', 12, true, true),
('Char siu bao', '叉烧包', 'carb', '1 piece', 8, true, true),
('Pineapple bun', '菠萝包', 'carb', '1 piece', 6, true, true),
('Egg tart', '蛋挞', 'carb', '1 piece', 4, true, true),
('Mooncake', '月饼', 'carb', '1 piece', 7, true, true),
('Sesame ball', '煎堆', 'carb', '1 piece', 3, true, true),
('Pumpkin', '南瓜', 'carb', '1 cup', 2, false, true),
('Taro', '芋头', 'carb', '1 cup', 3, true, true),
('Yam', '山药', 'carb', '1 cup', 2, true, true),
('Lotus root', '莲藕', 'carb', '1 cup', 3, true, true),
('Vermicelli noodles', '米粉', 'carb', '1 bowl', 2, true, true),
('Glass noodles', '粉丝', 'carb', '1 bowl', 1, true, true),
('E-fu noodles', '伊面', 'carb', '1 plate', 8, true, true),
('Udon', '乌冬面', 'carb', '1 bowl', 7, false, true),
('Ramen', '拉面', 'carb', '1 bowl', 10, false, true),
('Soba', '荞麦面', 'carb', '1 bowl', 8, false, true),
('Lasagna sheet', '千层面皮', 'carb', '2 sheets', 6, false, true),
('Couscous', '蒸粗麦粉', 'carb', '1 cup cooked', 6, false, true),
('Quinoa', '藜麦', 'carb', '1 cup cooked', 8, false, true),
('Barley', '大麦', 'carb', '1 cup cooked', 4, false, true),
('Millet', '小米', 'carb', '1 cup cooked', 6, false, true),
('Polenta', '玉米糊', 'carb', '1 cup', 3, false, true),
('Croissant', '牛角包', 'carb', '1 piece', 5, false, true),
('Scone', '司康饼', 'carb', '1 piece', 4, false, true),
('Pancake', '班戟', 'carb', '2 pieces', 6, true, true),
('Waffle', '窝夫', 'carb', '1 piece', 5, false, true),
('English muffin', '英式松饼', 'carb', '1 piece', 4, false, true),
('Dumpling skin', '饺子皮', 'carb', '10 pieces', 5, true, true),
('Spring roll wrapper', '春卷皮', 'carb', '4 pieces', 3, true, true),
('Pita bread', '皮塔饼', 'carb', '1 piece', 5, false, true),
('Naan', '印度烤饼', 'carb', '1 piece', 7, false, true),
('Ciabatta', '夏巴塔', 'carb', '1 piece', 6, false, true),
('French baguette', '法棍', 'carb', '3 slices', 6, false, true),
('Focaccia', '佛卡夏', 'carb', '1 piece', 5, false, true),
('Pretzel', '咸饼干', 'carb', '1 piece', 5, false, true),

-- ============== VEGETABLES (~30) ==============
('Broccoli', '西兰花', 'vegetable', '1 cup', 3, false, true),
('Spinach', '菠菜', 'vegetable', '1 cup cooked', 5, false, true),
('Bok choy', '白菜', 'vegetable', '1 cup', 2, true, true),
('Chinese broccoli / gai lan', '芥兰', 'vegetable', '1 cup', 3, true, true),
('Green beans', '四季豆', 'vegetable', '1 cup', 2, false, true),
('Mixed vegetables', '杂菜', 'vegetable', '1 cup', 3, false, true),
('Stir-fried vegetables', '炒杂菜', 'vegetable', '1 plate', 3, true, true),
('Tomato', '番茄', 'vegetable', '1 medium', 1, false, true),
('Cucumber', '青瓜', 'vegetable', '1 medium', 1, false, true),
('Corn kernels', '粟米粒', 'vegetable', '1 cup', 5, false, true),
('Mushrooms', '蘑菇', 'vegetable', '1 cup', 3, false, true),
('Eggplant', '茄子', 'vegetable', '1 cup', 1, false, true),
('Lettuce', '生菜', 'vegetable', '2 cups', 1, false, true),
('Carrots', '红萝卜', 'vegetable', '1 cup', 1, false, true),
('Bean sprouts', '芽菜', 'vegetable', '1 cup', 3, true, true),
('Winter melon', '冬瓜', 'vegetable', '1 cup', 1, true, true),
('Choy sum', '菜心', 'vegetable', '1 cup', 2, true, true),
('Water spinach / kangkong', '通菜', 'vegetable', '1 cup', 2, true, true),
('Chinese cabbage / napa', '大白菜', 'vegetable', '1 cup', 1, true, true),
('Mustard greens', '芥菜', 'vegetable', '1 cup', 2, true, true),
('Kale', '羽衣甘蓝', 'vegetable', '1 cup', 2, false, true),
('Asparagus', '芦笋', 'vegetable', '1 cup', 3, false, true),
('Cauliflower', '椰菜花', 'vegetable', '1 cup', 2, false, true),
('Bell pepper', '甜椒', 'vegetable', '1 medium', 1, false, true),
('Onion', '洋葱', 'vegetable', '1 medium', 1, false, true),
('Celery', '芹菜', 'vegetable', '1 cup', 1, false, true),
('Zucchini', '翠玉瓜', 'vegetable', '1 cup', 2, false, true),
('Bitter melon', '苦瓜', 'vegetable', '1 cup', 1, true, true),
('Pea shoots', '豆苗', 'vegetable', '1 cup', 3, true, true),
('Garlic chives', '韭菜', 'vegetable', '1 cup', 2, true, true),
('Leek', '韭葱', 'vegetable', '1 cup', 1, true, true),
('Snow peas', '荷兰豆', 'vegetable', '1 cup', 3, true, true),
('Watercress', '西洋菜', 'vegetable', '1 cup', 2, true, true),
('Daikon radish', '白萝卜', 'vegetable', '1 cup', 1, true, true),
('Seaweed / nori', '紫菜', 'vegetable', '1 sheet', 1, true, true),

-- ============== FRUITS (~20) ==============
('Apple', '苹果', 'fruit', '1 medium', 0.5, false, true),
('Banana', '香蕉', 'fruit', '1 medium', 1, false, true),
('Orange', '橙', 'fruit', '1 medium', 1, false, true),
('Mango', '芒果', 'fruit', '1 cup', 1, false, true),
('Watermelon', '西瓜', 'fruit', '1 cup', 1, true, true),
('Grapes', '葡萄', 'fruit', '1 cup', 1, false, true),
('Strawberry', '草莓', 'fruit', '1 cup', 1, false, true),
('Blueberries', '蓝莓', 'fruit', '1 cup', 1, false, true),
('Pineapple', '菠萝', 'fruit', '1 cup', 1, false, true),
('Kiwi', '奇异果', 'fruit', '2 pieces', 2, false, true),
('Dragon fruit', '火龙果', 'fruit', '1 piece', 2, true, true),
('Lychee', '荔枝', 'fruit', '10 pieces', 1, true, true),
('Pomelo', '柚子', 'fruit', '1 cup', 2, true, true),
('Papaya', '木瓜', 'fruit', '1 cup', 1, true, true),
('Guava', '番石榴', 'fruit', '1 medium', 2, true, true),
('Pear', '梨', 'fruit', '1 medium', 1, false, true),
('Peach', '桃', 'fruit', '1 medium', 1, false, true),
('Plum', '李子', 'fruit', '1 medium', 1, false, true),
('Cherries', '车厘子', 'fruit', '1 cup', 2, true, true),
('Longan', '龙眼', 'fruit', '10 pieces', 1, true, true),
('Durian', '榴莲', 'fruit', '1 cup', 4, true, true),
('Jackfruit', '菠萝蜜', 'fruit', '1 cup', 3, true, true),
('Persimmon', '柿子', 'fruit', '1 medium', 1, true, true),
('Asian pear / nashi', '雪梨', 'fruit', '1 medium', 1, true, true),
('Starfruit', '杨桃', 'fruit', '1 medium', 1, true, true),
('Custard apple', '释迦', 'fruit', '1 medium', 2, true, true),

-- ============== DAIRY & DRINKS (~20) ==============
('Whole milk', '全脂牛奶', 'dairy', '1 cup', 8, false, true),
('Skim milk', '脱脂牛奶', 'dairy', '1 cup', 8, false, true),
('Chocolate milk', '朱古力奶', 'dairy', '1 cup', 8, true, true),
('Yogurt', '酸奶', 'dairy', '1 cup', 8, false, true),
('Cheese, cheddar', '车打芝士', 'dairy', '1 slice', 7, false, true),
('Cheese, mozzarella', '水牛芝士', 'dairy', '1 oz', 6, false, true),
('Milk tea (HK style)', '港式奶茶', 'drink', '1 cup', 3, true, true),
('Juice, orange', '橙汁', 'drink', '1 cup', 2, false, true),
('Smoothie', '思慕雪', 'drink', '1 cup', 5, false, true),
('Coconut water', '椰青水', 'drink', '1 cup', 0.5, true, true),
('Lemon tea', '柠檬茶', 'drink', '1 cup', 0.5, true, true),
('Iced lemon tea', '冻柠茶', 'drink', '1 cup', 0.5, true, true),
('Yuanyang', '鸳鸯', 'drink', '1 cup', 3, true, true),
('Almond milk', '杏仁奶', 'drink', '1 cup', 1, false, true),
('Oat milk', '燕麦奶', 'drink', '1 cup', 3, false, true),
('Soy milk, sweetened', '甜豆浆', 'drink', '1 cup', 6, true, true),
('Vitasoy', '维他奶', 'drink', '1 box', 7, true, true),
('Pocari Sweat', '宝矿力水特', 'drink', '1 bottle', 0.5, true, true),
('Sports drink', '运动饮料', 'drink', '1 bottle', 0.5, false, true),
('Kombucha', '康普茶', 'drink', '1 cup', 1, false, true),
('Kefir', '克菲尔', 'drink', '1 cup', 9, false, true),
('Buttermilk', '酪乳', 'drink', '1 cup', 8, false, true),
('Heavy cream', '淡奶油', 'dairy', '2 tbsp', 1, false, true),
('Sour cream', '酸奶油', 'dairy', '2 tbsp', 1, false, true),
('Parmesan cheese', '帕马森芝士', 'dairy', '2 tbsp grated', 4, false, true),
('Feta cheese', '羊乳芝士', 'dairy', '1 oz', 4, false, true),
('Cream cheese', '忌廉芝士', 'dairy', '2 tbsp', 2, false, true),
('Greek yogurt drink', '希腊酸奶饮品', 'drink', '1 bottle', 12, false, true),

-- ============== OTHER / COMBOS (~20) ==============
('Pizza', '薄饼', 'other', '1 slice', 12, false, true),
('Hamburger', '汉堡包', 'other', '1 piece', 25, false, true),
('Sandwich', '三文治', 'other', '1 piece', 15, false, true),
('Burrito', '墨西哥卷', 'other', '1 piece', 20, false, true),
('Salad with chicken', '鸡肉沙律', 'other', '1 bowl', 25, false, true),
('Soup, chicken', '鸡汤', 'other', '1 bowl', 12, false, true),
('Soup, vegetable', '蔬菜汤', 'other', '1 bowl', 3, false, true),
('Wonton noodle soup', '云吞面', 'other', '1 bowl', 15, true, true),
('Beef brisket noodle soup', '牛腩面', 'other', '1 bowl', 25, true, true),
('Congee with pork', '皮蛋瘦肉粥', 'other', '1 bowl', 8, true, true),
('Dim sum: siu mai', '烧卖', 'other', '4 pieces', 10, true, true),
('Dim sum: har gow', '虾饺', 'other', '4 pieces', 8, true, true),
('Dim sum: cheung fun', '肠粉', 'other', '1 plate', 6, true, true),
('Hainan chicken rice', '海南鸡饭', 'other', '1 plate', 30, true, true),
('Curry chicken with rice', '咖喱鸡饭', 'other', '1 plate', 28, true, true),
('Tomato egg stir fry', '番茄炒蛋', 'other', '1 plate', 14, true, true),
('Mapo tofu', '麻婆豆腐', 'other', '1 plate', 15, true, true),
('Kung pao chicken', '宫保鸡丁', 'other', '1 plate', 25, false, true),
('Pad thai', '泰式炒河粉', 'other', '1 plate', 20, false, true),
('Sushi roll', '寿司卷', 'other', '8 pieces', 12, false, true),
('Ramen bowl', '日式拉面', 'other', '1 bowl', 22, false, true),
('Beef noodle soup', '牛肉面', 'other', '1 bowl', 26, true, true),
('Fish ball noodle', '鱼蛋粉', 'other', '1 bowl', 14, true, true),
('Yong tau foo', '酿豆腐', 'other', '1 bowl', 18, true, true),
('Claypot rice', '煲仔饭', 'other', '1 pot', 25, true, true),
('Char siu rice', '叉烧饭', 'other', '1 plate', 28, true, true),
('Pork chop rice', '猪扒饭', 'other', '1 plate', 30, true, true),
('Singapore noodles', '星洲炒米', 'other', '1 plate', 18, true, true),
('Fried wonton', '炸云吞', 'other', '6 pieces', 10, true, true),
('Baked pork chop rice', '焗猪扒饭', 'other', '1 plate', 32, true, true),
('Macaroni with ham soup', '火腿通粉', 'other', '1 bowl', 14, true, true),
('Beef satay noodle', '沙爹牛肉面', 'other', '1 bowl', 22, true, true);
